### ISSUE TITLE
Jetton -> pTON always throwing 709

### ISSUE THREAD

**Issue by wbelhomsi** [ston-fi/sdk#11]
Hi team, i was able to successfully swap pTON -> JETTON using `buildSwapProxyTonTxParams`, but when I'm trying to sell using `buildSwapJettonTxParams` I'm always hitting error 709. Also adding a specific forward gas is not respected much

```
  const jettonToTon = await router.buildSwapJettonTxParams({
    userWalletAddress: address,
    offerAmount: '76477536',
    offerJettonAddress: 'EQA2kCVNwVsil2EM2mB0SkXytxCqQjS4mttjDpnXmwG9T6bO',
    askJettonAddress: PROXY_TON,
    // minAskAmount: '143746115',
     minAskAmount: '0',
    forwardGasAmount: new TonWeb.utils.BN('600000000'),
    // query id to identify your transaction in the blockchain (optional)
    queryId: '13'
  });
```

Although `forwardGasAmount` is specified as `600000000`, gasAmount stayed `  amount: '300000000',`

```
  const { payload } = jettonToTon;

  const seqno = (await wallet.methods.seqno().call()) || 0;

  var result = await wallet.methods
    .transfer({
      secretKey: keyPair.secretKey,
      toAddress: jettonToTon.to,
      amount: BigNumber(jettonToTon.gasAmount).plus('250000000').toString(),
      seqno,
      payload,
    })
    .send();
```

This failed: https://tonviewer.com/transaction/1bc03470738f9f4646695aec43c19eb327364bc1f8ee45352b9dfbc30f4c73e9

Can someone please let me know what am I doing wrong?

Also is there a way to fetch the transaction hash from the `result`? right now I'm looping over the latest transactions and checking that the seqno passed

**Comment by pavel-rakhmanov** [comment]
same as https://github.com/ston-fi/sdk/issues/10
