### ISSUE TITLE
Extract Ton stuck on Jetton Wallet after a failed swap

### ISSUE THREAD

**Issue by wbelhomsi** [ston-fi/sdk#12]
If a swap fails the TON value sent to the Jetton wallet gets stuck in the Jetton wallet.
Is there a way to get those back?

https://tonviewer.com/transaction/14832f78f7edc1f3aa8b4a707924c82630d9457f6cc69d89c9d2ff888fcd89b8

**Comment by pavel-rakhmanov** [comment]
Yes, as a result of this transaction, TON is stuck on the `EQ...9yq` contract. Unfortunately, they cannot be returned.

Our users contacted us about this problem, and starting with SDK version 0.5, TON will be returned to the sender's wallet in case of an unsuccessful transaction.

**Comment by pavel-rakhmanov** [comment]
Yes, as a result of this transaction, TON is stuck on the `EQ...9yq` contract. Unfortunately, they cannot be returned.

Our users contacted us about this problem, and starting with SDK version 0.5, TON will be returned to the sender's wallet in case of an unsuccessful transaction.
