### ISSUE TITLE
Do you consider providing SDKs in other programming languages?

### ISSUE THREAD

**Issue by ZhangYiQiu** [ston-fi/sdk#14]
I'm using C#, but I can't find the corresponding SDK.

**Comment by pavel-rakhmanov** [comment]
Unfortunately, we do not plan to release SDKs for other programming languages right now or in the short term.

The main reason for this is the fact that although libraries for working with the TON blockchain are in other languages (https://docs.ton.org/develop/dapps/apis/sdk), the main activity that we observe takes place in the JS/TS space
