### ISSUE TITLE
There is no way to get `priceImpact`

### ISSUE THREAD

**Issue by troman29** [ston-fi/sdk#2]
Hello developers. Your SDK lacks the `priceImpact` calculation.

**Comment by pavel-rakhmanov** [comment]
This SDK is a thin wrapper on the contracts and doesn't provide any additional logic. 

To get additional data (such as price impact calculation), you can use our [public REST API](https://api.ston.fi/)

The method you are probably interested in is `/v1/swap/simulate` or `v1/reverse_swap/simulate`.  You can get more information about these methods in [Swagger](https://api.ston.fi/swagger-ui/)
