### ISSUE TITLE
Change logo

### ISSUE THREAD

**Issue by ohmarty** [ston-fi/sdk#20]
Hello

I launched a token through Ston.fi in January and renounced it. Unfortunate was a bad decision because token went through rebranding, and I need to somehow change the logo.

can anyone here help me with this task? 

Thank you in advance!

**Comment by pavel-rakhmanov** [comment]
This issue has nothing to do with the SDK, so I'll close it, but I recommend you contact [Stone.fi support chat](https://t.me/STONfi_support_bot) - they can forward your request to the developers who can solve it
