### ISSUE TITLE
Has the V2 API interface been launched?

### ISSUE THREAD

**Issue by kk20222202** [ston-fi/sdk#21]
Has the V2 API interface been launched? If so, what are the router contract address and the PTON contract address?

**Comment by pavel-rakhmanov** [comment]
We deployed DEX v2 contracts in testnet for now.

- Router v2: [kQCas2p939ESyXM_BzFJzcIe3GD5S0tbjJDj6EBVn-SPsEkN](https://testnet.tonviewer.com/kQCas2p939ESyXM_BzFJzcIe3GD5S0tbjJDj6EBVn-SPsEkN)
- pTon v2: [kQDwpyxrmYQlGDViPk-oqP4XK6J11I-bx7fJAlQCWmJB4m74](https://testnet.tonviewer.com/kQDwpyxrmYQlGDViPk-oqP4XK6J11I-bx7fJAlQCWmJB4m74)
- CPI Pool v2 TestRED/TestBLUE [kQCh4zsq8I85YK_5RYn33j52vHRArXAqrPyscbXncQ2hyLHd](https://testnet.tonviewer.com/kQCh4zsq8I85YK_5RYn33j52vHRArXAqrPyscbXncQ2hyLHd)

For it tests we also got a few test jettons:
 - TestRED: `kQDLvsZol3juZyOAVG8tWsJntOxeEZWEaWCbbSjYakQpuYN5`
 - TestGREEN: `kQCMGEfYTE-PkbmyVidhnc5rb2XSxUDevi8b2GBw3-Ke7w_p`
 - TestBLUE: `kQB_TOJSB7q3-Jm1O8s0jKFtqLElZDPjATs5uJGsujcjznq3`

To mint test tokens, send a minimum of 0.05 testnet Toncoin (TON) to each jetton minter. 
You will receive any excess back, along with 10 minted tokens.
