### ISSUE TITLE
Could not resolve dependency

### ISSUE THREAD

**Issue by steverogers180** [ston-fi/sdk#27]
```bash
npm error code ERESOLVE
npm error ERESOLVE unable to resolve dependency tree
npm error
npm error While resolving: [REDACTED]
npm error Found: @ton/ton@14.0.0
npm error node_modules/@ton/ton
npm error   @ton/ton@"^14.0.0" from the root project
npm error
npm error Could not resolve dependency:
npm error peer @ton/ton@"^13.9.0" from @ston-fi/sdk@2.0.0-rc.1
npm error node_modules/@ston-fi/sdk
npm error   @ston-fi/sdk@"2.0.0-rc.1" from the root project
npm error
npm error Fix the upstream dependency conflict, or retry
npm error this command with --force or --legacy-peer-deps
npm error to accept an incorrect (and potentially broken) dependency resolution
```

If I do --force or --legacy-peer-deps:

![image](https://github.com/user-attachments/assets/c8438187-dca0-4efb-85ba-6d01baabc733)

**Comment by pavel-rakhmanov** [comment]
Yep, the new major version of the @ton/ton package was released, and our expected version is still the previous one. 

We will release an updated version of the SDK when we fully check the compatibility with a new major @ton/ton package version, but for now, you can solve the issue locally using the [npm overrides](https://docs.npmjs.com/cli/v10/configuring-npm/package-json#overrides).

```
  "overrides": {
    "@ston-fi/sdk": {
      "@ton/ton": ">=14"
    }
  }
  ```

**Comment by pavel-rakhmanov** [comment]
The latest versions of the SDK ([1.0.2](https://www.npmjs.com/package/@ston-fi/sdk/v/1.0.2), [2.0.0-rc.2](https://www.npmjs.com/package/@ston-fi/sdk/v/2.0.0-rc.2)) will work with `@ton/ton:14` without any additional changes needed
