### ISSUE TITLE
Can Dex v1 work with pTON v2?

### ISSUE THREAD

**Issue by b1acKr0se** [ston-fi/sdk#30]
We are integrating pTON into our contract and would like to list our Token-pTON pair on Stonfi. Currently it looks like Dex v2 with pTON v2 support has not launched yet, but we already integrated the pTON v2 contract into ours since its source code is available. So we would like to know if Dex v1 can work with pTON v2 (specifically the providing liquidity operation)? If it does not, can you publish the source code for pTON v1 so we can better use it in our contracts?

Thank you very much.

**Comment by Oyase-shinobi** [comment]
Hello @b1acKr0se 
Hope you are doing well
I would love to engage in your team
