### ISSUE TITLE
swap referral 

### ISSUE THREAD

**Issue by kk20222202** [ston-fi/sdk#31]
Is there a rule regarding the commission that is sent to the referral address after a swap request is completed when a referral address is provided? If so, could you please provide the details?

**Comment by pavel-rakhmanov** [comment]
For the DEX v1 referral fee percent is defined at the moment of pool creation. You can get this value from [`getPoolData.refFee`](https://github.com/ston-fi/sdk/blob/main/src/contracts/dex/v1/PoolV1.ts#L284) filed, but in most pools, it equals `0.1%`.

For the DEX v2 referral fee percent could be configured for each swap via the `referralValue` parameter. 
With the following limitation:

> 'referralValue' should be in range [0, 100] BPS

**Comment by DevGoatX** [comment]
> For the DEX v1 referral fee percent is defined at the moment of pool creation. You can get this value from [`getPoolData.refFee`](https://github.com/ston-fi/sdk/blob/main/src/contracts/dex/v1/PoolV1.ts#L284) filed, but in most pools, it equals `0.1%` (10 BPS).
> 
> For the DEX v2 referral fee percent could be configured for each swap via the `referralValue` parameter. With the following limitation:
> 
> > 'referralValue' should be in range [0, 100] BPS

DEX v2 is working on the mainnet? I tested the swap of DEX v2 on the testnet. After that, I tried to test it on the mainnet. But I can never find the router address and proxyTon address. Do you know it? Then please let me know them.
Thanks in advance

**Comment by pavel-rakhmanov** [comment]
DEX v2 is currently only available in the testnet. We are still making some final improvements.

When it is released, we will make a big announcement across all our channels so you will not miss it.
