### ISSUE TITLE
Implemented in 6d77c9fb63b8202a7ee2ab71d430852b3fcc713b.

### ISSUE THREAD

**Issue by alijawan** [ston-fi/sdk#34]
Implemented in 6d77c9fb63b8202a7ee2ab71d430852b3fcc713b.

_Originally posted by @ton in https://github.com/ton/vim-bufsurf/issues/1#issuecomment-902399_

**Comment by pavel-rakhmanov** [comment]
I appreciate your taking the time to open this issue, but unfortunately, I'm forced to close it because of the lack of context 
ʅ（´◔౪◔）ʃ
