### ISSUE TITLE
[Question] How to parse the result of a routerV1 SwapTonToJetton transaction?

### ISSUE THREAD

**Issue by 3ww3-latiao** [ston-fi/sdk#38]
Here is my example:

```ts
const txParams = await router.getSwapTonToJettonTxParams({
    userWalletAddress: wallet.friendlyAddress,
    proxyTon,
    offerAmount,
    askJettonAddress: not,
    minAskAmount,
});
const res = await wallet.connecter.sendTransaction({
    validUntil: dayjs().add(10, 'm').unix(),
    messages: [
      {
        address: txParams.to.toString(),
        amount: txParams.value.toString(),
        payload: txParams.body?.toBoc().toString('base64'),
      },
    ],
});
```

I am swapping `notcoin` through `proxyTon` and sending the transaction using tonconnect. Everything seems fine, and the transaction is confirmed on the blockchain. However, I am having trouble parsing the BOC. I don't know the details of the response data, but I know that the `op` is `2281714092`.

**Comment by pavel-rakhmanov** [comment]
The cell creation is made in the `create*Body` contracts method. 

If, for some reason, you need to parse BOC you can take a look at the `createJettonTransferMessage` and `create*Body` functions and just read from the BOC value by values according to the way it was packed. 

For reference, you can take a look at [this code ](https://github.com/ston-fi/sdk/blob/main/src/contracts/dex/v1/RouterV1.ts#L555-L566) where we read data about the router from the BOC by knowing the order and type of values, stored in the BOC

**Comment by Secret1007** [comment]
I need to check the transaction status. If the status is true, I can proceed to the next step. So I need to parse the BOC. I guess I can get the transaction hash from it, am I right?
