### ISSUE TITLE
Unable to execute get method. Got exit_code: -13

### ISSUE THREAD

**Issue by mianshenglee** [ston-fi/sdk#44]
i'm doing the swap according to the ston doc DEX v2 guide, code like this, any can help?
const client = new TonClient({
  endpoint: "https://testnet.toncenter.com/api/v2/jsonRPC",
});

const router = client.open(
  DEX.v2_1.Router.create(
    "kQALh-JBBIKK7gr0o4AVf9JZnEsFndqO0qTCyT-D-yBsWk0v" // CPI Router v2.1.0
  )
);

const proxyTon = pTON.v2_1.create(
  "kQACS30DNoUQ7NfApPvzh7eBmSZ9L4ygJ-lkNWtba8TQT-Px" // pTON v2.1.0
);

// swap 1 TON to TestRED but not less than 1 nano TestRED
const txParams = await router.getSwapTonToJettonTxParams({
  userWalletAddress: "", // ! replace with your address
  proxyTon: proxyTon,
  offerAmount: toNano("1"),
  askJettonAddress: "kQDLvsZol3juZyOAVG8tWsJntOxeEZWEaWCbbSjYakQpuYN5", // TestRED
  minAskAmount: "1",
});

but got error: 
G:\workspace\mason\gitee\banban-node-rest-server\node_modules\@ton\ton\dist\client\TonClient.js:42
            throw Error('Unable to execute get method. Got exit_code: ' + res.exit_code);
                  ^
source-map-support.js:722
Error: Unable to execute get method. Got exit_code: -13
    at TonClient.runMethod (G:\workspace\mason\gitee\banban-node-rest-server\node_modules\@ton\ton\dist\client\TonClient.js:42:19)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Object.get (G:\workspace\mason\gitee\banban-node-rest-server\node_modules\@ton\ton\dist\client\TonClient.js:364:26)
    at async JettonMinter.getWalletAddress (G:\workspace\mason\gitee\banban-node-rest-server\node_modules\@ston-fi\sdk\src\contracts\core\JettonMinter.ts:12:20)
    at async Promise.all (index 1)
    at async _class.getSwapJettonToJettonTxParams (G:\workspace\mason\gitee\banban-node-rest-server\node_modules\@ston-fi\sdk\src\contracts\dex\v2_1\router\BaseRouterV2_1.ts:199:7)

**Comment by pavel-rakhmanov** [comment]
The -13 error code from the TON API means that it tries to execute contracts get method that does not exist. 
The reason is usually the wrong address passed to the build/send function.

Since the code you provided looks like the example from our docs, the only address that needs to be added is the user's wallet address, which might be an issue. 

For example, here is the code with my test wallet that works

```ts
import { TonClient, toNano } from "@ton/ton";
import { DEX, pTON } from "@ston-fi/sdk";

const client = new TonClient({
  endpoint: "https://testnet.toncenter.com/api/v2/jsonRPC",
});

const router = client.open(
  DEX.v2_1.Router.create(
    "kQALh-JBBIKK7gr0o4AVf9JZnEsFndqO0qTCyT-D-yBsWk0v" // CPI Router v2.1.0
  )
);

const proxyTon = pTON.v2_1.create(
  "kQACS30DNoUQ7NfApPvzh7eBmSZ9L4ygJ-lkNWtba8TQT-Px" // pTON v2.1.0
);

// swap 1 TON to TestRED but not less than 1 nano TestRED
const txParams = await router.getSwapTonToJettonTxParams({
  userWalletAddress: 'UQAQnxLqlX2B6w4jQzzzPWA8eyWZVZBz6Y0D_8noARLOaEAn',
  proxyTon: proxyTon,
  offerAmount: toNano("1"), // 1 TON
  askJettonAddress: "kQDLvsZol3juZyOAVG8tWsJntOxeEZWEaWCbbSjYakQpuYN5", // TestRED
  minAskAmount: "1", // 1 nano TestRED
});

console.log(txParams);
// ^
// {
//   to: EQBbJjnahBMGbMUJwhAXLn8BiigcGXMJhSC0l7DBhdYABqox,
//   value: 1310000000n,
//   body: x{01F3835D000000000000000043B9ACA00800213E25D52AFB03D61C468679E67AC078F64B32AB20E7D31A07FF93D002259CD1}
//    x{6664DE2A801B38307351A48AE63D06CC20508BDEE329E92CF3AD2061C4DE98840B2FB64AC59000427C4BAA55F607AC388D0CF3CCF580F1EC96655641CFA6340FFF27A0044B39A200084F89754ABEC0F58711A19E799EB01E3D92CCAAC839F4C681FFE4F4008967340000000033A4E8644_}
//     x{101800213E25D52AFB03D61C468679E67AC078F64B32AB20E7D31A07FF93D002259CD00000051_}
// }
```
