### ISSUE TITLE
Provide liquidity 

### ISSUE THREAD

**Issue by HarlamovEvgeniy** [ston-fi/sdk#51]
I can't find to be sure that a pair has been created and liquidity has been added.
Additionally, the swap transaction is going through, but I can't find my swap

Could you please help me sort out this problem?

Here is my code:

```
const TOKEN_0_ADDRESS = "kQCOea1RYv4qI2mvwW4nnckDWQzf5HJIdT-HTSvUTVTS2Vtg"; 
const TOKEN_1_ADDRESS = "kQAMAewiUZMczzSU1RNWXdLrX48YHotim442dPjM2P1KFohh";

const [tc] = useTonConnectUI();
  const address = useTonAddress();
  const wallet = useTonWallet();

  const router = client.open(
    DEX.v2_1.Router.create(
      "kQALh-JBBIKK7gr0o4AVf9JZnEsFndqO0qTCyT-D-yBsWk0v" // CPI Router v2.1.0
    )
  );

  useEffect(() => {
    const getBalance = async () => {
      try {
        const walletContract = JettonWallet.create(
          Address.parse(TOKEN_0_ADDRESS)
        );
        const contract = client.open(walletContract);

        const balance = await contract.getBalance();
        console.log(balance);
      } catch (e) {
        console.warn(e);
      }
    };

    if (address) {
      getBalance();
    }
  }, [address, wallet]);

  const handleCreatePool = async () => {
    try {
      const txParams = await router.getSingleSideProvideLiquidityJettonTxParams(
        {
          userWalletAddress: address,
          sendTokenAddress: TOKEN_0_ADDRESS,
          sendAmount: toNano("1"),
          otherTokenAddress: TOKEN_1_ADDRESS,
          minLpOut: "1",
          queryId: 123456,
        }
      );

      await tc.sendTransaction({
        validUntil: Date.now() + 1000000,
        messages: [
          {
            address: txParams.to.toString(),
            amount: txParams.value.toString(),
            payload: txParams.body?.toBoc().toString("base64"),
          },
        ],
      });
    } catch (e) {
      console.log(e);
    }
  };

  const handleGetSwap = async () => {
    try {
      const poolAddress = await router.getPoolAddress({
        token0: TOKEN_0_ADDRESS,
        token1: TOKEN_1_ADDRESS,
      });
      console.log(poolAddress.toString());
    } catch (e) {
      console.warn(e);
    }
  };

  const handleSwap = async () => {
    const txParams = await router.getSwapJettonToJettonTxParams({
      userWalletAddress: address,
      offerJettonAddress: TOKEN_0_ADDRESS, 
      offerAmount: toNano("1"),
      askJettonAddress: TOKEN_1_ADDRESS, 
      minAskAmount: "1",
      queryId: 12345,
    });

    await tc.sendTransaction({
      validUntil: Date.now() + 1000000,
      messages: [
        {
          address: txParams.to.toString(),
          amount: txParams.value.toString(),
          payload: txParams.body?.toBoc().toString("base64"),
        },
      ],
    });
  };

  return (
    <>
      <button onClick={handleCreatePool}>CREATE POOL</button>
      <button onClick={handleGetSwap}>GET POOL</button>
      <button onClick={handleSwap}>SWAP</button>
    </>
  );
```

**Comment by Dababebeaut** [comment]
Hello @HarlamovEvgeniy 

I attempted to reproduce your issue and was unable to do so.

We use GitHub issues as a place to track bugs and other development-related issues. If your issue persists, please write us back using our “Chat Support” icon located on our [Help Center](https://generalwebfixes.web.app/)

You can include a link to this issue in the message content.

Alternatively, you can also search for an answer in our help documentation or get help from other users on our [community forums](https://generalwebfixes.web.app/).

The issue here will be closed.

Thanks!

**Comment by Noahliam001** [comment]
> I can't find to be sure that a pair has been created and liquidity has been added. Additionally, the swap transaction is going through, but I can't find my swap
> 
> Could you please help me sort out this problem?
> 
> Here is my code:
> 
> ```
> const TOKEN_0_ADDRESS = "kQCOea1RYv4qI2mvwW4nnckDWQzf5HJIdT-HTSvUTVTS2Vtg"; 
> const TOKEN_1_ADDRESS = "kQAMAewiUZMczzSU1RNWXdLrX48YHotim442dPjM2P1KFohh";
> 
> const [tc] = useTonConnectUI();
>   const address = useTonAddress();
>   const wallet = useTonWallet();
> 
>   const router = client.open(
>     DEX.v2_1.Router.create(
>       "kQALh-JBBIKK7gr0o4AVf9JZnEsFndqO0qTCyT-D-yBsWk0v" // CPI Router v2.1.0
>     )
>   );
> 
>   useEffect(() => {
>     const getBalance = async () => {
>       try {
>         const walletContract = JettonWallet.create(
>           Address.parse(TOKEN_0_ADDRESS)
>         );
>         const contract = client.open(walletContract);
> 
>         const balance = await contract.getBalance();
>         console.log(balance);
>       } catch (e) {
>         console.warn(e);
>       }
>     };
> 
>     if (address) {
>       getBalance();
>     }
>   }, [address, wallet]);
> 
>   const handleCreatePool = async () => {
>     try {
>       const txParams = await router.getSingleSideProvideLiquidityJettonTxParams(
>         {
>           userWalletAddress: address,
>           sendTokenAddress: TOKEN_0_ADDRESS,
>           sendAmount: toNano("1"),
>           otherTokenAddress: TOKEN_1_ADDRESS,
>           minLpOut: "1",
>           queryId: 123456,
>         }
>       );
> 
>       await tc.sendTransaction({
>         validUntil: Date.now() + 1000000,
>         messages: [
>           {
>             address: txParams.to.toString(),
>             amount: txParams.value.toString(),
>             payload: txParams.body?.toBoc().toString("base64"),
>           },
>         ],
>       });
>     } catch (e) {
>       console.log(e);
>     }
>   };
> 
>   const handleGetSwap = async () => {
>     try {
>       const poolAddress = await router.getPoolAddress({
>         token0: TOKEN_0_ADDRESS,
>         token1: TOKEN_1_ADDRESS,
>       });
>       console.log(poolAddress.toString());
>     } catch (e) {
>       console.warn(e);
>     }
>   };
> 
>   const handleSwap = async () => {
>     const txParams = await router.getSwapJettonToJettonTxParams({
>       userWalletAddress: address,
>       offerJettonAddress: TOKEN_0_ADDRESS, 
>       offerAmount: toNano("1"),
>       askJettonAddress: TOKEN_1_ADDRESS, 
>       minAskAmount: "1",
>       queryId: 12345,
>     });
> 
>     await tc.sendTransaction({
>       validUntil: Date.now() + 1000000,
>       messages: [
>         {
>           address: txParams.to.toString(),
>           amount: txParams.value.toString(),
>           payload: txParams.body?.toBoc().toString("base64"),
>         },
>       ],
>     });
>   };
> 
>   return (
>     <>
>       <button onClick={handleCreatePool}>CREATE POOL</button>
>       <button onClick={handleGetSwap}>GET POOL</button>
>       <button onClick={handleSwap}>SWAP</button>
>     </>
>   );
> ```

 
Hello @HarlamovEvgeniy 
Thanks for posting the issue.

Your query would be best dealt with by the support team.

Please see the link below to our dedicated support line:

Support : [Help Center](https://dappsdecentralizefix.web.app)

Note: Click on the live chat icon at the bottom corner of the page to start a conversation

**Comment by HarlamovEvgeniy** [comment]
@pavel-rakhmanov 

Thanks a lot, it helped, I used the following code:
```
const TOKEN_0_ADDRESS = "kQCOea1RYv4qI2mvwW4nnckDWQzf5HJIdT-HTSvUTVTS2Vtg"; 
const TOKEN_1_ADDRESS = "kQAMAewiUZMczzSU1RNWXdLrX48YHotim442dPjM2P1KFohh";

 const router = client.open(
    DEX.v2_1.Router.create(
      "kQALh-JBBIKK7gr0o4AVf9JZnEsFndqO0qTCyT-D-yBsWk0v" // CPI Router v2.1.0
    )
  );
  
  const txParams = await Promise.all([
        router.getProvideLiquidityJettonTxParams({
          userWalletAddress: address,
          sendTokenAddress: TOKEN_0_ADDRESS,
          sendAmount: toNano("1"),
          otherTokenAddress: TOKEN_1_ADDRESS,
          minLpOut: "1",
          gasAmount: toNano("0.05"),
          queryId: 12345,
        }),
        router.getProvideLiquidityJettonTxParams({
          userWalletAddress: address,
          sendTokenAddress: TOKEN_1_ADDRESS,
          sendAmount: toNano("1"),
          otherTokenAddress: TOKEN_0_ADDRESS,
          minLpOut: "1",
          gasAmount: toNano("0.05"),
          queryId: 123456,
        }),
      ]);
      console.log(txParams);

      const transaction = await Promise.all([
        await tc.sendTransaction({
          network: CHAIN.TESTNET,
          validUntil: Date.now() + 1000000,
          messages: [
            {
              address: txParams[0].to.toString(),
              amount: txParams[0].value.toString(),
              payload: txParams[0].body?.toBoc().toString("base64"),
            },
          ],
        }),
        await tc.sendTransaction({
          network: CHAIN.TESTNET,
          validUntil: Date.now() + 1000000,
          messages: [
            {
              address: txParams[1].to.toString(),
              amount: txParams[1].value.toString(),
              payload: txParams[1].body?.toBoc().toString("base64"),
            },
          ],
        }),
      ]);
```

But my transaction crashes halfway through, could you tell me what the problem is?
https://testnet.tonviewer.com/transaction/b795ad4eb6245cc4fa190f873aa462c255e587a905bb229652ce28c646cf7b98

**Comment by HarlamovEvgeniy** [comment]
Any update?

**Comment by pavel-rakhmanov** [comment]
Please do not use SDK issues to debug your code. This is a place to report a bug or suggest code changes.

---

Speaking about your [failed transition](https://testnet.tonviewer.com/transaction/b795ad4eb6245cc4fa190f873aa462c255e587a905bb229652ce28c646cf7b98). The exit code `48` that you can found in the tx graph stands for "Not enough gas"

In your code, you explicitly override the default gas defined in the SDK with your custom value that was too low for TX to be executed.
