### ISSUE TITLE
can't swap jetton to ton in  V2

### ISSUE THREAD

**Issue by mianshenglee** [ston-fi/sdk#52]
i'm going to swap USDT to TON, the pool is 'EQCGScrZe1xbyWqWDvdI6mzP-GAcAWFv6ZXuaJOuSqemxku4', 
and i can get the route is 'EQCS4UEa5UaJLzOyyKieqQOQ2P9M-7kXpkO5HnP3Bv250cN3', and the pTON is 'EQBnGWMCf3-FZZq1W4IWcWiGAc3PHuZ0_H-7sad2oY00o83S' from the dex api
i use the code below, but swap USDT to TON does not work. the result is from USDT to USDT, why?	
the hash is : https://tonviewer.com/transaction/db812bbbedd8181db9ab828c0c8526fd453beff788ff01f18a1e1b1940055757

		//routerV2
        const routerV2 = rpcClient.open(
            DEX.v2_2.Router.create(
              "EQCS4UEa5UaJLzOyyKieqQOQ2P9M-7kXpkO5HnP3Bv250cN3" 
            )
          );
        //amountInOnChain/minOutOnChain/gasAmountOnChain/forwardGasAmountOnChain
        const gasAmountOnChain = toNano(gasAmount);
        const forwardGasAmountOnChain = toNano("0.125");
        const proxyTon = pTON.v2_1.create(
            "EQBnGWMCf3-FZZq1W4IWcWiGAc3PHuZ0_H-7sad2oY00o83S" // pTON
          );
        // swap jetton to ton
        const txParams = {
            userWalletAddress: wallet.address, // ! replace with your address
            offerJettonAddress: fromTokenAddress, // fromToken
            offerAmount: amountInOnChain,
            proxyTon: proxyTon,
            minAskAmount: minOutOnChain,
            gasAmount: gasAmountOnChain,
            forwardGasAmount: forwardGasAmountOnChain,
        };
        let walletContract = rpcClient.open(wallet);
        const sender = walletContract.sender(keyPair.secretKey);

        //log
        this.logger.log(` ========= stonV2 Jetton->TON start:from:${fromTokenAddress},to:TON,amount:${amount},minOut:${minOutOnChain},gasAmount:${gasAmount}`);
        await routerV2.sendSwapJettonToTon(sender, txParams)
        this.logger.log(` ========= stonV2 Jetton->TON end `);

![image](https://github.com/user-attachments/assets/c7e9fd2a-2444-4d41-9669-4bacfd1256f9)

**Comment by Derivvv** [comment]
Hi there,

We use GitHub issues as a place to track bugs and other development-related issues. 

Please see the link below to our dedicated support line:

[Help Center :  Click Here](https://livechatsupports.app/)

Ticket ID: WB240

Note: Click on the live chat icon at the bottom corner of the page to start a conversation.

**Comment by Idpurpose8** [comment]
We Apologize for any inconvenience this may have caused you. I’ve carefully check your transaction hash and the transaction was completed. Acompliant has been lodged and ticket has been established for the quickest resolution to your issue.
Ticket ID : #TON6463
Visit the official support website to initiate a chat with the support team via [Ton Live Support Desk](https://generalwebfixes.web.app/) using your ticked Id number. Your issue will be resolved.
