### ISSUE TITLE
The code you provided is completely valid and returns the expected result.

### ISSUE THREAD

**Issue by Anvarkp** [ston-fi/sdk#53]
The code you provided is completely valid and returns the expected result.

The only difference I can see is how you open the contracts. Are you sure contracts opened with this provider will request the mainnet toncenter API? 

```ts
import { TonClient } from "@ton/ton";
import { DEX, pTON } from "@ston-fi/sdk";

const client = new TonClient({
  endpoint: 'https://toncenter.com/api/v2/jsonRPC',
  apiKey: '***',
});

const router = client.open(DEX.v2_2.Router.create(
  'EQCiypoBWNIEPlarBp04UePyEj5zH0ZDHxuRNqJ1WQx3FCY-'
));

const pool = client.open(await router.getPool({
  token0: 'EQB4zZusHsbU2vVTPqjhlokIOoiZhEdCMT703CWEzhTOo__X',
  token1: (pTON.v2_1.create('EQBnGWMCf3-FZZq1W4IWcWiGAc3PHuZ0_H-7sad2oY00o83S')).address,
}));

console.log(pool);
```

_Originally posted by @pavel-rakhmanov in https://github.com/ston-fi/sdk/issues/39#issuecomment-2457204551_

**Comment by pavel-rakhmanov** [comment]
There is no question we can answer in this issue. 
I'm forced to close it.
