### ISSUE TITLE
Error when creating a swap

### ISSUE THREAD

**Issue by sharkset** [ston-fi/sdk#7]
I'm trying to do a simple TON -> USDT swap on STON.fi.  It seems to be more difficult than anticipated.  See below for function.  Any advise will be appreciated.  

```
async function stonfi(mnemonic) {

 const keyPair = await mnemonicToWalletKey(mnemonic.split(' '));
 const tonweb = new TonWeb(new TonWeb.HttpProvider('https://toncenter.com/api/v2/jsonRPC', { apiKey: 'e4cf6......' }));

 const WalletClass = tonweb.wallet.all.v4R2;

 const wallet = new WalletClass(tonweb.provider, {
  publicKey: keyPair.publicKey,
 });

 const address = await wallet.getAddress();

 const JETTON0 = 'EQBynBO23ywHy_CgarY9NK9FTz0yDsG82PtcbSTQgGoXwiuA'; //USDT;
 const PROXY_TON = 'EQCM3B12QK1e4yZSf8GtBRT0aLMNyEsBc_DhVfRRtOEffLez';

 const router = new Router(tonweb.provider, {
  revision: ROUTER_REVISION.V1,
  address: ROUTER_REVISION_ADDRESS.V1,
 });

 const tonToJettonTxParams = await router.buildSwapProxyTonTxParams({
  // address of the wallet that holds TON you want to swap
  userWalletAddress: address,
  proxyTonAddress: PROXY_TON,
  // amount of the TON you want to swap
  offerAmount: new TonWeb.utils.BN('1000000'),
  // address of the jetton you want to receive
  askJettonAddress: JETTON0,
  // minimal amount of the jetton you want to receive as a result of the swap.
  // If the amount of the jetton you want to receive is less than minAskAmount
  // the transaction will bounce
  minAskAmount: new TonWeb.utils.BN(1),
  // query id to identify your transaction in the blockchain (optional)
  queryId: 12345,
  // address of the wallet to receive the referral fee (optional)
  referralAddress: undefined,
 });

 const seqno = (await wallet.methods.seqno().call()) || 0;

 var result = await wallet.methods
  .transfer({
   secretKey: keyPair.secretKey,
   toAddress: ROUTER_REVISION_ADDRESS.V1,
   amount: '1000000',
   seqno: seqno,
   payload: tonToJettonTxParams.payload
  })
  .send();
}
```

The transaction has this error: 

> Error: http provider parse response error
>     at Function.parseResponse (C:\dev\node\swapStonFi\myapp\node_modules\tonweb\src\providers\HttpProviderUtils.js:51:25)
>     at HttpProvider.call2 (C:\dev\node\swapStonFi\myapp\node_modules\tonweb\src\providers\index.js:154:34)
>     at processTicksAndRejections (node:internal/process/task_queues:95:5)
>     at async JettonMinter.getJettonWalletAddress (C:\dev\node\swapStonFi\myapp\node_modules\tonweb\src\contract\token\ft\JettonMinter.js:112:24)
>     at async wt.buildSwapProxyTonTxParams (C:\dev\node\swapStonFi\myapp\node_modules\@ston-fi\sdk\src\contracts\dex\router\Router.ts:320:36)
>     at async stonfi (C:\dev\node\swapStonFi\myapp\src\index.ts:31:37) {
>   result: {
>     '@type': 'smc.runResult',
>     gas_used: 370,
>     stack: [ [Array] ],
>     exit_code: 11,
>     '@extra': '1710039253.351542:3:0.5662450514253229'
>   }
> }

**Comment by dusanpracaex** [comment]
Hi I'm now working on exactly this part.
I have similar errors and let's discuss.
live:.cid.3b21a5193c351677
is my skkyype address

**Comment by nhatmai3686** [comment]
@sharkset how you fix this issue?

**Comment by Aurora3014** [comment]
I have solved TON => Jetton but jetton => TON is not working.
HOW??

**Comment by ccwwbb0** [comment]
> @sharkset how you fix this issue?


you just need set apiKey at "TonWeb.HttpProvider()"
