### ISSUE TITLE
What version of nodejs does SDK require?

### ISSUE THREAD

**Issue by zzy7dennis** [ston-fi/sdk#8]
What version of nodejs does SDK require?
![008C805C-5B8F-4236-A8C6-67470E1E39B0](https://github.com/ston-fi/sdk/assets/96457509/126faa90-485f-4b34-b068-40106220e450)

**Comment by Divaneto02** [comment]
https://github.com/ston-fi/sdk/issues/8#issue-2197067554

**Comment by alijawan** [comment]
> What version of nodejs does SDK require?
> ![008C805C-5B8F-4236-A8C6-67470E1E39B0](https://github.com/ston-fi/sdk/assets/96457509/126faa90-485f-4b34-b068-40106220e450)
> 
>
