### ISSUE TITLE
Error making swap from JETTON1/JETTON2 with .buildSwapJettonTxParams()

### ISSUE THREAD

**Issue by thinh-pham-klarda** [ston-fi/sdk#9]
Hi developers,
Recently, I've tried the ston.fi sdk. 
Basically, when I'm trying to swap from TonProxy to other token using 

`buildSwapProxyTonTxParams`

The function works fine. However, when I tried to swap from JETTON1/JETTON2 using

`buildSwapJettonTxParams`

The transaction is successfully send but **FAILED**. Here is the transaction hash: https://tonviewer.com/transaction/26fa5541793a9ea2aa9f1564942538257faf5c0ad5ca8e5f31665d79b6136369.

Here is the code

`
const swapTxParams 
= await router.buildSwapJettonTxParams({

        userWalletAddress: WALLET_ADDRESS,
        
        offerJettonAddress: JETTON0,
        
        offerAmount: new TonWeb.utils.BN('100000'),
        
        askJettonAddress: PROXY_TON,
        
        minAskAmount: 0,
        
        queryId: 12345,
        
        referralAddress: undefined,
});

      if(seqno !== undefined) {
        const transfer = await wallet.methods.transfer({
          secretKey: secretKey,
          toAddress: swapTxParams.to,
          amount: swapTxParams.gasAmount, 
          seqno: seqno,
          payload: swapTxParams.payload,
          sendMode: 3,
         });
        const transferSended = await transfer.send();  // send transfer query to blockchain
        console.log('finish: ', transferSended);
    }
`
I wonder are there any developers meet this issue? I would love to discuss.

**Comment by pavel-rakhmanov** [comment]
According to what I see from [your tx](https://tonviewer.com/transaction/26fa5541793a9ea2aa9f1564942538257faf5c0ad5ca8e5f31665d79b6136369), you are trying to make a jetton swap with custom `gasAmount` (0.0001 TON). This is too low; the default value for this gas constant is 0.3 TON.

If you are looking for a way to cut gas loss, take a look at our [doc section](https://docs.ston.fi/docs/developer-section/dev-guide/swap#recommended-gas-values) that describes recommended gas amounts for each type of swap

**Comment by pavel-rakhmanov** [comment]
According to what I see from [your tx](https://tonviewer.com/transaction/26fa5541793a9ea2aa9f1564942538257faf5c0ad5ca8e5f31665d79b6136369), you are trying to make a jetton swap with custom `gasAmount` of (0.0001 TON). This is too low; the default value for this gas constant is 0.3 TON.

If you are looking for a way to cut gas loss, take a look at our [doc section](https://docs.ston.fi/docs/developer-section/dev-guide/swap#recommended-gas-values) that describes recommended gas amounts for each type of swap

**Comment by pavel-rakhmanov** [comment]
same as https://github.com/ston-fi/sdk/issues/10
